# Generated by Django 5.0.3 on 2024-04-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='books.genre'),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Collected'), (4, 'Complete'), (5, 'Declined')], default=1),
        ),
    ]
