# Generated by Django 5.0.3 on 2024-04-07 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_genre_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'permissions': (('all_actions_genre', 'Can create, update, delete genre'),)},
        ),
    ]
