# Generated by Django 5.0.3 on 2024-04-08 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
    ]
