# Generated by Django 5.0.3 on 2024-04-15 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('all_actions_book', 'Can create, update, delete book'),)},
        ),
        migrations.AlterModelOptions(
            name='borrowrequest',
            options={'permissions': (('process_request', 'Can confirm, reject, complete borrow request'),)},
        ),
    ]
