# Generated by Django 5.0.3 on 2024-04-15 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_options_alter_borrowrequest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name'], 'permissions': (('all_actions_author', 'Can create, update, delete author'),)},
        ),
        migrations.AlterModelOptions(
            name='borrowrequest',
            options={'ordering': ['request_date'], 'permissions': (('process_request', 'Can confirm, reject, complete borrow request'),)},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'permissions': (('all_actions_genre', 'Can create, update, delete genre'),)},
        ),
    ]
