# Generated by Django 5.0.3 on 2024-04-17 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_author_options_alter_borrowrequest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeBorrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_date', models.DateField(auto_now_add=True)),
                ('borroew_result', models.BooleanField()),
                ('refusal_message', models.CharField(blank=True, max_length=350, null=True)),
                ('viewed', models.BooleanField(default=False)),
                ('borrow_recuest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.borrowrequest')),
            ],
        ),
    ]
