# Generated by Django 5.0.3 on 2024-04-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_rename_borroew_result_noticeborrow_borrow_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticeborrow',
            old_name='borrow_recuest',
            new_name='borrow_request',
        ),
    ]
