# Generated by Django 5.0.3 on 2024-04-18 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_rename_borrow_recuest_noticeborrow_borrow_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticeborrow',
            options={'ordering': ['viewed']},
        ),
    ]
