# Generated by Django 5.0.3 on 2024-04-18 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_noticeborrow_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowrequest',
            options={'ordering': ['-request_date'], 'permissions': (('process_request', 'Can confirm, reject, complete borrow request'),)},
        ),
        migrations.AlterModelOptions(
            name='noticeborrow',
            options={'ordering': ['-notice_date']},
        ),
    ]
