# Generated by Django 5.0.3 on 2024-04-19 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_borrowrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticeborrow',
            options={'ordering': ['viewed', '-notice_date']},
        ),
    ]
